/*
 * Name: Hari Prasad Dhonju Shrestha
 * LUID: L20352046
 * Program Assessment: This program successfully add the event to the server and save the data to the text file.
 * 						When quering the event the program successfully print the list of event in server terminal.
 */
/*
* This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hist.h"

void hist_rpc_1(char *host) {
	CLIENT *clnt;
	int *result_1;
	rpcparam add_1_arg;
	char **result_2;
	rpcparam query_1_arg;

#ifndef	DEBUG
	clnt = clnt_create(host, HIST_RPC, HIST_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
#endif	/* DEBUG */

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror(clnt, "call failed");
	}
	result_2 = query_1(&query_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror(clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy(clnt);
#endif	 /* DEBUG */
}

int add(CLIENT *clnt, int date, int month, char* description) {

	rpcparam param;
	int * result;

	param.date = date;
	param.month = month;
	param.description = description;

	result = add_1(&param, clnt);
	if (result == NULL) {
		fprintf(stderr, "Trouble calling remote RPC.");
	} else {
		printf("Event added in server\n");
	}
	return (*result);

}

/*query part */

void Query(CLIENT *clnt, int date, int month) {
	rpcparam param;
	char * * result;
	int i;
	param.date = date;
	param.month = month;
	result = query_1(&param, clnt);

	if (result == NULL) {
		fprintf(stderr, "Trouble calling remote RPC_Query.");
	}
	printf("%s \n", *result);
}

int main(int argc, char *argv[]) {
	CLIENT *clnt;
	char *host;
	int date;
	int month;
	char* description;

	if (argc <= 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	clnt = clnt_create(argv[1], HIST_RPC, HIST_VERSION, "udp");

	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(argv[1]);
		exit(1);
	}

	date = atoi(argv[3]);
	month = atoi(argv[4]);
	description = argv[5];

	if (strcmp(argv[2], "add") == 0) {
		add(clnt, date, month, description);
	} else if (strcmp(argv[2], "query") == 0) {
		Query(clnt, date, month);
	} else {
		printf("check %s", argv[2]);
		printf("Invalid event\n");
		exit(1);
	}
	exit(0);
}
