/*
 * Name: Hari Prasad Dhonju Shrestha
 * LUID: L20352046
 * Program Assessment: This program successfully add the event to the server and save the data to the text file.
 * 						When quering the event the program successfully print the list of event in server terminal.
 */
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include "hist.h"
#include <string.h>

typedef struct database {
	int mnth;
	int yr;

	char _data[100000];
} database;

int *
add_1_svc(rpcparam *argp, struct svc_req *rqstp) {
	static int result;

	int dateval;
	int monthval;
	char* description;

	dateval = argp->date;
	monthval = argp->month;
	description = argp->description;

	FILE *fptr;
	char buffer[200];

	fptr = (fopen("history.txt", "a+"));

	if (fptr == NULL) {
		printf("Error opening file!");
		exit(1);
	} else {
		fseek(fptr, 0, SEEK_END);
		if (ftell(fptr) == 0) {
			fprintf(fptr, "\%02d", dateval);
			fprintf(fptr, " ");
			fprintf(fptr, "%02d", monthval);
			fprintf(fptr, " %s", description);
		} else {
			fprintf(fptr, "\n%02d", dateval);
			fprintf(fptr, " ");
			fprintf(fptr, "%02d", monthval);
			fprintf(fptr, " %s", description);
		}
		fseek(fptr, 0, SEEK_SET);
	}

	fclose(fptr);
	printf("Event added successfully! \n");
	return &result;
}

char **
query_1_svc(rpcparam *argp, struct svc_req *rqstp) {
	static char * result;
	result = malloc(sizeof(char) * 1000000);
	char * buffer;
	buffer = malloc(sizeof(char) * 1000000);
	FILE * fp;

	database hist_data;
	char inp[100], line[100], temp[6];
	char buf1[10];
	char buf2[10];

	snprintf(buf1, 10, "%02d", argp->date);
	snprintf(buf2, 10, "%02d", argp->month);
	strcat(buf1, " ");
	strcat(buf1, buf2);

	fp = fopen("history.txt", "r+");

	if (fp == NULL) {
		exit(EXIT_FAILURE);
	}

	while (fgets(line, sizeof(line), fp)) {
		if (strlen(line) < 5)
			continue;
		strncpy(temp, line, 5);
		temp[5] = 0;

		char *foo;
		foo = line;
		foo += 5;			// for printing from 6th characters
		if (!strcmp(buf1, temp)) {
			strcpy(buffer, foo);
			strcat(buffer, "\n");
			strcat(result, buffer);
		}
	}
	printf("%s", result);
	fclose(fp);
	return &result;
}
